import { Component } from '@angular/core';

@Component({
  selector: 'app-askprompt',
  templateUrl: './askprompt.component.html',
  styleUrls: ['./askprompt.component.css']
})
export class AskpromptComponent {
  userPrompt: string = '';
  aiResponse: string = 'Your AI response will appear here...';

  // Method to trigger AI response generation
  generateResponse() {
    this.aiResponse = 'This is a sample response generated by AI.';
    // Implement your AI call logic here
  }
}
