import { Component } from '@angular/core';

@Component({
  selector: 'app-ask-prompt',
  templateUrl: './ask-prompt.component.html',
  styleUrls: ['./ask-prompt.component.css']
})
export class AskPromptComponent {
  userPrompt: string = '';
  aiResponse: string = 'Your AI response will appear here...';

  // Method to trigger AI response generation
  generateResponse() {
    this.aiResponse = 'This is a sample response generated by AI.';
    // Implement your AI call logic here
  }
}
